baseURL = "https://amandacarneiro.netlify.com"
languageCode = "en-us"
title = "Amanda Carneiro Muller"
theme = "mero"
disableKinds = ["taxonomyTerm"]

[module]
  [module.hugoVersion]
    extended = false
    min = '0.80.0'

[params]
  dateFormat = "2021-01-02" 
  author = "Amanda Carneiro"
  description = "Personal information"
  mainImage = "images/main.jpeg"

[params.introduction]
   text = "Here you can find more about me"

[params.social]
  [[params.social.list]]
  class = "fab"
  icon = "fa-linkedin-in"
  url = "#https://www.linkedin.com/in/carneiro-amanda"

  [[params.social.list]]
  class = "fab"
  icon = "fa-github"
  url = "#https://github.com/amandacarneiro/"
    

[params.footer]
  message = "&copy; 2023 Amanda Carneiro Muller"
